name: Build
on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
      - container/Dockerfile
      - .github/workflows/deploy-image.yml
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
      - container/Dockerfile
      - .github/workflows/deploy-image.yml

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      u-boot: ${{ steps.query.outputs.u-boot }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Query available board configs
        id: query
        run: |
          echo "u-boot=$(./bsp json profile u-boot)" >> $GITHUB_OUTPUT
  build_u-boot:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [ u-boot ]
        profiles: ${{fromJSON(needs.query.outputs.u-boot)}}
    steps:
      - name: Build
        uses: radxa-repo/bsp@main
        with:
          target: ${{ matrix.targets }}
          edition: ${{ matrix.profiles }}
          artifacts: true
